# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Documents\Programmation\PublicProject\patcher_999_PC\ihm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 86)
        MainWindow.setMinimumSize(QtCore.QSize(642, 86))
        MainWindow.setMaximumSize(QtCore.QSize(642, 86))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ressource/DreamteamLogo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_process = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_process.setGeometry(QtCore.QRect(300, 40, 75, 23))
        self.pushButton_process.setMaximumSize(QtCore.QSize(16777215, 16777211))
        self.pushButton_process.setObjectName("pushButton_process")
        self.pushButton_browse = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browse.setGeometry(QtCore.QRect(560, 10, 75, 23))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.label_done = QtWidgets.QLabel(self.centralwidget)
        self.label_done.setGeometry(QtCore.QRect(440, 40, 121, 20))
        self.label_done.setObjectName("label_done")
        self.label_process = QtWidgets.QLabel(self.centralwidget)
        self.label_process.setGeometry(QtCore.QRect(440, 40, 191, 21))
        self.label_process.setObjectName("label_process")
        self.fileEdit_path = FileEdit(self.centralwidget)
        self.fileEdit_path.setGeometry(QtCore.QRect(10, 10, 541, 20))
        self.fileEdit_path.setObjectName("fileEdit_path")
        self.pushButton_choix_fichier = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_choix_fichier.setGeometry(QtCore.QRect(20, 40, 91, 23))
        self.pushButton_choix_fichier.setObjectName("pushButton_choix_fichier")
        self.pushButton_choix_image = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_choix_image.setGeometry(QtCore.QRect(120, 40, 91, 23))
        self.pushButton_choix_image.setObjectName("pushButton_choix_image")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_browse, self.pushButton_process)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "999 patch automatique"))
        self.pushButton_process.setText(_translate("MainWindow", "process"))
        self.pushButton_browse.setText(_translate("MainWindow", "browse"))
        self.label_done.setText(_translate("MainWindow", "done !"))
        self.label_process.setText(_translate("MainWindow", "in process..."))
        self.pushButton_choix_fichier.setText(_translate("MainWindow", "Choisir fichiers"))
        self.pushButton_choix_image.setText(_translate("MainWindow", "Choisir images"))
from fileEdit import FileEdit
import ressource_rc
